### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by tuzmusic** [dpa99c/react-native-launch-navigator#16]
I'm unable to install with yarn (my preferred) or npm.

```
// YARN WITHOUT SUDO FAILS WITH EACCES

[14:03:01] (map-app-options) QMGElectroNative
// ♥ yarn add react-native-launch-navigator
yarn add v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-maps@0.24.2" has unmet peer dependency "prop-types@^15.0 || ^16.0".
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.14.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev".
error An unexpected error occurred: "EACCES: permission denied, mkdir '/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/define-property/node_modules/kind-of'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

// YARN WITH SUDO FAILS

[14:03:36] (map-app-options) QMGElectroNative
// ♥ sudo yarn add react-native-launch-navigator
yarn add v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-maps@0.24.2" has unmet peer dependency "prop-types@^15.0 || ^16.0".
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.14.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev".
[4/4] 🔨  Building fresh packages...
[-/5] ⠈ waiting...
[2/5] ⠈ fsevents
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
error /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator
Output:
react-native-launch-navigator: auto-linking
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.
child_process.js:677
    throw err;
    ^

Error: Command failed: react-native link react-native-launch-navigator
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.

    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at Object.helpers.runCommand (/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator/scripts/install_helpers.js:17:5)
    at Object.<anonymous> (/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator/scripts/postinstall.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)

// NPM WITHOUT SUDO

[13:57:09] (map-app-options) QMGElectroNative
// ♥ npm install --save react-native-launch-navigator
Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/TuzMacbookPro2017/.npm/_cacache/index-v5/b6/21' by a newer version or is no longer required

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/TuzMacbookPro2017/.npm/_logs/2019-07-30T17_59_59_580Z-debug.log

// NPM WITH SUDO

[13:59:59] (map-app-options) QMGElectroNative
// ♥ sudo npm install --save react-native-launch-navigator
Password:
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated 
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> react-native-launch-navigator@1.0.5 preuninstall /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator
> node scripts/preuninstall.js

react-native-launch-navigator: skipping auto-unlinking (not linked)
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/tsc as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/typescript
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/tsserver as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/typescript
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/semver as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/semver
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/prettier as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/prettier
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/jest as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/jest-cli
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/esvalidate as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/esprima
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/esparse as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/esprima
npm WARN rm not removing /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/.bin/react-native as it wasn't installed by /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/@react-native-community/cli

> fsevents@1.2.9 install /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@11.12.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/build'
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:988:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents
node-pre-gyp ERR! node -v v11.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)

> core-js@3.1.4 postinstall /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/@babel/register/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> react-native-launch-navigator@1.0.5 postinstall /Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator
> node scripts/postinstall.js

react-native-launch-navigator: auto-linking
warn Package redux has been ignored because it contains invalid configuration. Reason: Cannot find module 'redux/package.json'
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.
child_process.js:677
    throw err;
    ^

Error: Command failed: react-native link react-native-launch-navigator
warn Package redux has been ignored because it contains invalid configuration. Reason: Cannot find module 'redux/package.json'
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.

    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at Object.helpers.runCommand (/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator/scripts/install_helpers.js:17:5)
    at Object.<anonymous> (/Users/TuzMacbookPro2017/Development/QMG-local/QMGElectroNative/node_modules/react-native-launch-navigator/scripts/postinstall.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
npm WARN react-redux@6.0.1 requires a peer of redux@^2.0.0 || ^3.0.0 || ^4.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-launch-navigator@1.0.5 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-launch-navigator@1.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/TuzMacbookPro2017/.npm/_logs/2019-07-30T18_03_01_749Z-debug.log
```

My package.json:
```
{
  "name": "QMGElectroNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/geolocation": "^1.4.2",
    "axios": "^0.18.0",
    "axios-mock-adapter": "^1.16.0",
    "email-validator": "^2.0.4",
    "react": "16.8.6",
    "react-dom": "^16.8.6",
    "react-native": "0.60.4",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-global-font": "^1.0.2",
    "react-native-indicators": "^0.13.0",
    "react-native-maps": "~0.24.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.9.1",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-saga": "^1.0.2",
    "redux-thunk": "^2.3.0",
    "sugar": "^2.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "flow-bin": "^0.100.0",
    "flow-typed": "^2.6.0",
    "jest": "^24.8.0",
    "jest-mock-axios": "^3.0.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "prettier-eslint": "^8.8.2",
    "react-test-renderer": "16.8.6",
    "redux-saga-tester": "^1.0.468"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by dpa99c** [comment]
`react-native@0.60.x` support has been added in `react-native-launch-navigator@1.0.6`
