### ISSUE TITLE
Install Trouble ?

### ISSUE THREAD

**Issue by Tilenozz** [dpa99c/react-native-launch-navigator#23]
hello ,
i tried to install this package on 2 computers and the result is the same.

npm install --save react-native-launch-navigator

> react-native-launch-navigator@1.0.6 postinstall E:\rn\Beta2.0\Hurry\node_modules\react-native-launch-navigator
> node scripts/postinstall.js

internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at Object.<anonymous> (E:\rn\Beta2.0\Hurry\node_modules\react-native-launch-navigator\scripts\ios.link_helpers.js:45:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\rn\Beta2.0\Hurry\node_modules\react-native-launch-navigator\scripts\postinstall.js:3:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-launch-navigator@1.0.6 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-launch-navigator@1.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is this my trouble or package ?
Regards

**Comment by dpa99c** [comment]
Looking at your path it looks like you're using Windows and a have a directory name containing a `.` - `Beta2.0`. Given the [line number referenced in the stacktrace](https://github.com/dpa99c/react-native-launch-navigator/blob/master/scripts/ios.link_helpers.js#L45), I would speculate this is screwing up the nodejs path module from resolving the filepath.
Try removing the dot from your directory name.

Also try cloning the [example project](https://github.com/dpa99c/react-native-launch-navigator-example) to a drive root directory and building this as a known working reference.

**Comment by Tilenozz** [comment]
You was right ! tyvm

**Comment by mikson7** [comment]
Hello,
I have exactly the same issue during the installation. I don't have any `.` in my directory name, I've also tried to install the package in few different directories - every time obtaining the same message (The "path" argument must be of type string. Received type object).
